name: Docker Image CI

on:
  [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build .  -t my-function-image
    - name: Run container and wait for startup
      run: |
          docker run -d --name test-container my-function-image
          sleep 5
